version: 2

build:
  image: 'testing'

sphinx:
    configuration: docs/conf.py

formats: all

python:
    version: '3.9'
    install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
