from .status import Status as Status
from fractions import Fraction

class Convert:
    @classmethod
    def ts2f(cls, ts: str, fps: Fraction) -> int: ...
    @classmethod
    def f2ts(cls, f: int, fps: Fraction, *, precision: int = ...) -> str: ...
    @classmethod
    def seconds2ts(cls, s: float, *, precision: int = ...) -> str: ...
    @classmethod
    def f2assts(cls, f: int, fps: Fraction) -> str: ...
    @staticmethod
    def f2seconds(f: int, fps: Fraction) -> float: ...
    @staticmethod
    def ts2seconds(ts: str) -> float: ...
    @staticmethod
    def seconds2f(s: float, fps: Fraction) -> int: ...
    @staticmethod
    def composets(h: float, m: float, s: float, *, precision: int = ...) -> str: ...
