from pathlib import Path
from typing import Any

class VPath(Path):
    def format(self, *args: Any, **kwargs: Any) -> VPath: ...
    def set_track(self, track_number: int) -> VPath: ...
    def to_str(self) -> str: ...
