name: ci-tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
            python-version: 3.9

      - name: Install VapourSynth
        uses: Irrational-Encoding-Wizardry/install-vapoursynth-action@v0.1
        with:
            version: latest
            cache: true

      - name: Install Meson & Ninja
        run: |
          python -m pip install --upgrade pip
          sudo python -m pip install meson
          sudo apt-get update
          sudo apt-get install ninja-build
      - name: Install Ffmpeg
        run: |
          git clone https://github.com/FFmpeg/FFmpeg --branch release/4.4 --depth 1
          pushd FFmpeg
          ./configure --enable-gpl --enable-version3 --disable-static --enable-shared --disable-all --disable-autodetect --enable-avcodec --enable-avformat --enable-swresample --enable-swscale --disable-asm --disable-debug
          make -j2
          sudo make install -j2
          popd
          rm -rf FFmpeg
      - name: Install VapourSynth and vps libs
        run: |
          git clone https://github.com/l-smash/l-smash --depth 1
          pushd l-smash
          mv configure configure.old
          sed 's/-Wl,--version-script,liblsmash.ver//g' configure.old >configure
          chmod +x configure
          ./configure --disable-static
          make lib -j2
          sudo make install-lib -j2
          popd
          rm -rf l-smash
          git clone https://github.com/sekrit-twc/zimg --branch v3.0 --depth 1
          pushd zimg
          ./autogen.sh
          ./configure --disable-static --disable-simd
          make -j2
          sudo make install -j2
          popd
          rm -rf zimg
          git clone https://github.com/vapoursynth/vapoursynth --depth 1 vapoursynth-build
          pushd vapoursynth-build
          ./autogen.sh
          ./configure --disable-x86-asm --disable-vsscript --disable-vspipe --disable-python-module --disable-plugins
          make -j2
          sudo make install -j2
          popd
          rm -rf vapoursynth-build
          git clone https://github.com/AkarinVS/L-SMASH-Works.git --depth 1
          pushd L-SMASH-Works/VapourSynth
          sudo meson build
          sudo ninja -C build
          sudo ninja -C build install
          sudo cp build/libvslsmashsource.so /usr/lib/vapoursynth/libvslsmashsource.so
          popd
          sudo apt-get install zlib1g-dev
          git clone https://github.com/FFMS/ffms2.git --depth 1
          pushd ffms2
          ./autogen.sh
          ./configure
          make -j2
          sudo make install -j2
          sudo cp /usr/local/lib/libffms2.so /usr/lib/vapoursynth/libffms2.so
          popd
          rm -rf ffms2

      - name: Install vardautomation
        run: |
            pip install -r requirements.txt
            python setup.py install

      - name: Running pytest
        run: |
          pip install pytest
          pytest
